In [1]:
from glob import glob
from pathlib import Path

import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from utilities import *

pd.set_option('display.max_rows', 500)


### Import data

In [2]:
data = {
    "smadc": get_SMADC_folder_data(),
    "annotated": get_annotated_data_folder_data(),
    "dart": get_dart_folder_data(),
    "aoc": get_arabic_dialects_dataset_folder_data(),
}

### Import lexicons

In [3]:
pd.DataFrame.from_dict(get_arabic_lexicon_data(), orient="index").T.columns.values

array(['anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise'],
      dtype=object)

In [4]:
# Add dialects
lx = pd.DataFrame(columns=["Word", "Dialect", "Emotion"])
for path in glob("dialect_lexicon/*"):
    with open(path, "r", encoding="utf8") as file:
        dialect, emotion = Path(path).stem.split("_")
        temp = pd.DataFrame(columns=["Word", "Dialect", "Emotion"])
        temp[["Word", "Dialect", "Emotion"]] = [[line.replace("\n", "") for line in file.readlines()], dialect, emotion]
        lx = pd.concat([lx, temp])

# MSA
emotions = {"anger", "joy", "sadness", "disgust", "surprise", "fear"}
MSA = pd.DataFrame.from_dict(get_arabic_lexicon_data(), orient="index") \
    .T \
    .melt(value_vars=emotions, var_name="Emotion", value_name="Word") \
    .dropna()

# Finish lx
lx.reset_index(inplace=True, drop=True)
lx

d:\Softwarez\Anaconda\envs\emotion_research\lib\site-packages\numpy\core\fromnumeric.py:3199: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return asarray(a).ndim
d:\Softwarez\Anaconda\envs\emotion_research\lib\site-packages\numpy\core\fromnumeric.py:2007: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape
d:\Softwarez\Anaconda\envs\emotion_research\lib\site-packages\numpy\core\fromnumeric.py:3199: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays 

Word Dialect   Emotion
0         هكرهك     EGY     anger
1          تخرس     EGY     anger
2          اخرس     EGY     anger
3          جلنف     EGY     anger
4          بزيئ     EGY     anger
5         اندال     EGY     anger
6           ندل     EGY     anger
7           عرص     EGY     anger
8           وسخ     EGY     anger
9        يمسخكم     EGY   disgust
10         تقرف     EGY   disgust
11         مؤرف     EGY   disgust
12    متقرفوناش     EGY   disgust
13      تقرفينا     EGY   disgust
14       هيقرفه     EGY   disgust
15        صرصار     EGY   disgust
16   هخافميخافش     EGY      fear
17      مبنخافش     EGY      fear
18        تزغرط     EGY       joy
19        هيرضى     EGY       joy
20        تمزحو     EGY       joy
21     ميحرمناش     EGY       joy
22        متشكر     EGY       joy
23      هتستمتع     EGY       joy
24         هفرح     EGY       joy
25        هتضحك     EGY       joy
26       مريحني     EGY       joy
27        حزنان     EGY   sadness
28       مبزعلش     EGY   sadness
29        مخنوق     EGY   sadness
30        اتبكي     EGY   sadness
31         يبكو     EGY   sadness
32         هعيط     EGY   sadness
33        نكدية     EGY   sadness
34        مصحتش     EGY   sadness
35      مضيقاني     EGY   sadness
36       متزعلش     EGY   sadness
37     بتضايقنى     EGY   sadness
38     ماتوقعوش     EGY  surprise
39       هتفاجئ     EGY  surprise
40       هفاجئك     EGY  surprise
41     اتفاجئنا     EGY  surprise
42        مصخره     GLF     anger
43         كريه     GLF     anger
44        متخلف     GLF     anger
45        مبزره     GLF     anger
46         كرهي     GLF     anger
47          لطخ     GLF     anger
48         حقير     GLF     anger
49         يقهر     GLF     anger
50          عمى     GLF     anger
51         يلعن     GLF     anger
52          غبي     GLF     anger
53        لعنبو     GLF     anger
54        يلعنم     GLF     anger
55        شخصنة     GLF     anger
56         اذلف     GLF     anger
57          يغث     GLF   disgust
58          لطخ     GLF   disgust
59         بذيء     GLF   disgust
60         أشمط     GLF   disgust
61          جرذ     GLF   disgust
62        جرثوم     GLF   disgust
63          وصخ     GLF   disgust
64        حثاله     GLF   disgust
65          ازق     GLF   disgust
66         عجيب     GLF      fear
67        مفجوع     GLF      fear
68         مروع     GLF      fear
69       متخوفة     GLF      fear
70         مخوف     GLF      fear
71       خوفتني     GLF      fear
72       خايفين     GLF      fear
73         منغص     GLF      fear
74         ينحب     GLF       joy
75       ماقصرت     GLF       joy
76       سالخير     GLF       joy
77        مشكور     GLF       joy
78      لاهنتوا     GLF       joy
79       عقبالك     GLF       joy
80       يهنيكم     GLF       joy
81         نكتة     GLF       joy
82          لهف     GLF       joy
83       بشوفتك     GLF       joy
84       يافرحه     GLF       joy
85       ضايقني     GLF   sadness
86          شكى     GLF   sadness
87       يبكيني     GLF   sadness
88         ضايق     GLF   sadness
89          قهر     GLF   sadness
90        تبكيك     GLF   sadness
91        يخذلك     GLF   sadness
92          خنق     GLF   sadness
93        خذلان     GLF   sadness
94          قسى     GLF   sadness
95        يحزني     GLF   sadness
96         أحزن     GLF   sadness
97         أبكى     GLF   sadness
98         غثيث     GLF   sadness
99           حز     GLF   sadness
100       فاقدن     GLF   sadness
101        أفتك     GLF   sadness
102         هول     GLF  surprise
103        مهول     GLF  surprise
104       ترويع     GLF  surprise
105        أعجب     GLF  surprise
106      مفاجئه     GLF  surprise
107         هبل     GLF  surprise
108        فجأه     GLF  surprise

# Training utils

In [5]:
def generate_classifier(
        lx: pd.DataFrame, 
        MSA: pd.DataFrame, 
        emotion: str, 
        add_MSA_data: bool=False, 
        add_other_data: bool=False
    ) -> MultinomialNB:
    emotions = {"anger", "joy", "sadness", "disgust", "surprise", "fear"}
    assert emotion in emotions, f"{emotion} is not {emotions}"

    x, y = lx[lx["Emotion"] == "anger"][["Word", "Dialect"]].values.T

    if add_MSA_data:
        # Add MSA to all dialects (Messes up results!)
        x_msa = MSA[MSA["Emotion"] == "anger"]["Word"].values.T
        for dialect in np.unique(y):
            x, y = np.concatenate((x, x_msa)), np.concatenate((y, len(x_msa) * [dialect]))

    if add_other_data:
        # Add other data
        other = lx[lx["Emotion"] != "anger"]["Word"].values
        x, y = np.concatenate((x, other)), np.concatenate((y, len(other) * ["OTHER"]))
    
    print("Input data: ", np.unique(y, return_counts=True))

    clf = Pipeline([
        ('vect', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ('clf', MultinomialNB()),
    ])

    clf.fit(x, y)
    return clf

# Results

In [6]:
test = [
    "غضب",
    "شخص",
    "نذل", # This word is in the GLF lexicon
    "هكرهك", # This word is in the EGY lexicon
    "هو ليه ما حدش بيقولنا إننا بنتكلم لغة جميلة و فيها تعبيرات و أمثال و مفردات في منتهى الذكاء و خفة الدم ... ليه كل اللي بنسمعه إنها  عامية و سوقية و لغة شوارع .. المصري من أحلى لغات الدنيا بالفعل و على ودن المصري هي الأجمل على الإطلاق",
    "مبيشتغلش ماتشين ورا بعض لازم فاصل وللودي عنده زي الدوري",
]


### just lexicon

In [7]:
anger_clf = generate_classifier(lx, MSA, "anger")
anger_clf.predict(test), anger_clf.predict_proba(test)

Input data:  (array(['EGY', 'GLF'], dtype=object), array([ 9, 15], dtype=int64))


(array(['GLF', 'GLF', 'GLF', 'EGY', 'GLF', 'GLF'], dtype='<U3'),
 array([[0.375     , 0.625     ],
        [0.375     , 0.625     ],
        [0.375     , 0.625     ],
        [0.58646617, 0.41353383],
        [0.375     , 0.625     ],
        [0.375     , 0.625     ]]))

### add OTHER class

In [8]:
anger_clf = generate_classifier(lx, MSA, "anger", add_other_data=True)
anger_clf.predict(test), anger_clf.predict_proba(test)

Input data:  (array(['EGY', 'GLF', 'OTHER'], dtype=object), array([ 9, 15, 85], dtype=int64))


(array(['OTHER', 'OTHER', 'OTHER', 'OTHER', 'OTHER', 'OTHER'], dtype='<U5'),
 array([[0.08256881, 0.13761468, 0.77981651],
        [0.08256881, 0.13761468, 0.77981651],
        [0.08256881, 0.13761468, 0.77981651],
        [0.21480536, 0.17027254, 0.61492209],
        [0.08256881, 0.13761468, 0.77981651],
        [0.08256881, 0.13761468, 0.77981651]]))

### add MSA data to lexicon

In [9]:
anger_clf = generate_classifier(lx, MSA, "anger", add_MSA_data=True)
anger_clf.predict(test), anger_clf.predict_proba(test)

Input data:  (array(['EGY', 'GLF'], dtype=object), array([1101, 1107], dtype=int64))


(array(['GLF', 'GLF', 'GLF', 'EGY', 'GLF', 'GLF'], dtype='<U3'),
 array([[0.49949357, 0.50050643],
        [0.4986413 , 0.5013587 ],
        [0.4986413 , 0.5013587 ],
        [0.66621636, 0.33378364],
        [0.4986413 , 0.5013587 ],
        [0.4986413 , 0.5013587 ]]))

### add OTHER class
### add MSA data to lexicon

In [10]:
anger_clf = generate_classifier(lx, MSA, "anger", add_other_data=True, add_MSA_data=True)
anger_clf.predict(test), anger_clf.predict_proba(test)

Input data:  (array(['EGY', 'GLF', 'OTHER'], dtype=object), array([1101, 1107,   85], dtype=int64))


(array(['GLF', 'GLF', 'GLF', 'EGY', 'GLF', 'GLF'], dtype='<U5'),
 array([[0.49750546, 0.49858818, 0.00390636],
        [0.480157  , 0.48277366, 0.03706934],
        [0.480157  , 0.48277366, 0.03706934],
        [0.6299375 , 0.31565421, 0.05440829],
        [0.480157  , 0.48277366, 0.03706934],
        [0.480157  , 0.48277366, 0.03706934]]))

## Classifier classifies everything as GLF unless very clear